content/urls.py
from django.conf.urls import url
from content.views import article
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    #стартовая страница
    # url(r'^$', home, name='home'),
    # # страница контента
    # url(r'^content/$', content, name='content'),
    # #конкретная статья
    url(r'^content/get/(?P<article_id>\d+)/$', article, name='content'),
    # #Все статьи
    # url(r'^content/articles/$', articles, name='articles'),
    # #Статьи по страницам
    # url(r'^articles/page/(\d+)/$', articles),
    # #Страница с контактами
    # url(r'^contacts/$', contacts, name='contacts'),



     ]
# url(r'^articles/all/$', articles),
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gidrosave/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^', include('about.urls')),
    url(r'^', include('content.urls')),
    url(r'^', include('article.urls')),
]

home/urls.py
from django.conf.urls import url
from home.views import home
from home.views import about
from home.views import content
from home.views import article
from home.views import contact
from home.views import blog
from home.views import blogpost
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    # стартовая страница
    url(r'^$', home, name='home'),
    # страница о компании
    url(r'^about-us/$', about, name='about'),
    #конкретная статья
    url(r'^content/get/(?P<article_id>\d+)/$', article, name='article'),
    #Все статьи
     url(r'^content/$', content, name='articles'),
    # Все статьи блога
    url(r'^articles/$', blog, name='blog'),
    #Статьи по страницам блога
    url(r'^articles/page/(\d+)/$', blog),
    #конкретная статья блога
    url(r'^articles/get/(?P<article_id>\d+)/$', blogpost, name='post'),
    #Страница с контактами
    url(r'^contact/$', contact, name='contact'),
     ]
# url(r'^articles/all/$', articles),
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class About(models.Model):
    class Meta():
        db_table = 'about'
        verbose_name = u'О компании'
        verbose_name_plural = u'О компании'


    about_title = models.CharField(max_length=60, verbose_name=u'Заголовок')
    about_text = RichTextUploadingField(verbose_name=u'Текст')
    about_image = models.ImageField(null=True, blank=True, upload_to="images/",
                                      verbose_name=u'Изображение', )

    def __str__(self):
        return self.about_text[:50] + "..."

    def bit(self):
        if self.about_image:
            return u'<img src="%s" width="70"/>' % self.about_image.url
        else:
            return u'(none)'



    bit.short_descriptio = u'Изображение'
    bit.allow_tags = True


class ShortAbout(models.Model):
   class Meta():
       db_table = 'shortabout'

   short_text = models.TextField(verbose_name=u'Краткое описание')
   short_article = models.ForeignKey(About)

content/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from embed_video.fields import EmbedVideoField


class Article(models.Model):
    article_title = models.CharField(max_length=60, verbose_name='Заголовок')
    article_text = RichTextUploadingField(verbose_name='Текст статьи')
    # можно нафик убрать время или вообще всё
    article_date = models.DateTimeField(verbose_name="Дата и время")
    # можно убрать нафик
    goals_1 = models.TextField(null=True, blank=True, verbose_name='Цели 1')
    goals_2 = models.TextField(null=True, blank=True, verbose_name='Цели 2')
    is_active = models.BooleanField(default=True)
    article_likes = models.IntegerField(default=0)
    # article_image = models.ImageField(null=True, blank=True, upload_to="images/",
    #                                   verbose_name=u'Изображение', )
    video = EmbedVideoField(null=True, blank=True, verbose_name=u'Видео', )


    def __str__(self):
        return self.article_title
    #
    # def bit(self):
    #     if self.article_image:
    #         return u'<img src="%s" width="70"/>' % self.article_image.url
    #     else:
    #         return u'(none)'
    #
    # bit.short_descriptio = u'Изображение'
    # bit.allow_tags = True
    class Meta():
        db_table = "article"
        verbose_name = 'статьи'
        verbose_name_plural = 'статьи'
        ordering = ['-article_date']

class Features(models.Model):
   class Meta():
       db_table = 'features'

   features_text = models.TextField(null=True, blank=True, verbose_name='Особенности')
   features_article = models.ForeignKey(Article)

class ContentImages(models.Model):
    class Meta():
        db_table = 'content_images'
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    article = models.ForeignKey(Article, null=True, blank=True, default=None)
    image = models.ImageField(null=True, blank=True, upload_to="images/content/",
                                       verbose_name=u'Изображение', )
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.id

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from embed_video.fields import EmbedVideoField


class Home(models.Model):
    home_title = models.CharField(max_length=60, verbose_name='Заголовок')
    home_text = RichTextUploadingField(verbose_name='Текст статьи')
    # можно нафик убрать время или вообще всё
    home_date = models.DateTimeField(verbose_name="Дата и время")
    home_image_1 = models.ImageField(null=True, blank=True, upload_to="images/",
                                      verbose_name=u'Изображение 1', )
    home_image_2 = models.ImageField(null=True, blank=True, upload_to="images/",
                                     verbose_name=u'Изображение 2', )
    home_image_3 = models.ImageField(null=True, blank=True, upload_to="images/",
                                     verbose_name=u'Изображение 3', )
    home_image_4 = models.ImageField(null=True, blank=True, upload_to="images/",
                                     verbose_name=u'Изображение 4', )
    home_image_5 = models.ImageField(null=True, blank=True, upload_to="images/",
                                     verbose_name=u'Изображение 5', )
    video = EmbedVideoField(null=True, blank=True, verbose_name=u'Видео', )


    def __str__(self):
        return self.home_text

    # def bit(self):
    #     if self.home_image:
    #         return u'<img src="%s" width="70"/>' % self.home_image.url
    #     else:
    #         return u'(none)'
    #
    # bit.short_descriptio = u'Изображение'
    # bit.allow_tags = True
#     class Meta():
#         db_table = "home"
#         verbose_name = 'статьи'
#         verbose_name_plural = 'статьи'
#         # ordering = ['-home_date']
#
# class HomeImg(models.Model):
#    class Meta():
#        db_table = 'homeimages'
#        verbose_name = 'картинки под статью'
#
#    home_image = models.ImageField(null=True, blank=True, upload_to="images/",
#                                   verbose_name=u'Изображение', )
#    img_text = models.TextField(null=True, blank=True,)
#    img_article = models.ForeignKey(Home)
#
#    def bit(self):
#        if self.home_image:
#            return u'<img src="%s" width="70"/>' % self.home_image.url
#        else:
#            return u'(none)'
#
#    bit.short_descriptio = u'Изображение'
#    bit.allow_tags = True
#

home/forms.py
from django import forms
# Модель формы обратной связи
# class ContactForm(forms.Form):
#     subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
#     sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
#     message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
#     copy = forms.BooleanField(required=False)


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    # the new bit we're adding
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['content'].label = "What do you want to say?"

content/views.py
from django.shortcuts import render
from content.models import *

def article (request, article_id):
    article = Article.objects.get(id=article_id)
    return render(request, 'content/article.html', locals())

home/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from .forms import ContactForm
from django.http.response import HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
# #from django.template.loader import get_template
# #from django.template import Context
from django.shortcuts import render_to_response
from home.models import Home
from about.models import About, ShortAbout
from content.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from article.models import *



def home(request,article_id=1):
    """Домашняя страница нашего проекта"""
    contexts = Home.objects.all()
    # images = HomeImg.objects.all()
    # краткое о нас
    abouts = ShortAbout.objects.all()
    return render(request, 'index.html',locals())


def about(request):
    """Страница о компании"""
    context = About.objects.all()
    # краткое о нас
    abouts = ShortAbout.objects.all()
    return render(request, 'about.html', locals())

def content(request):
    images_main = ContentImages.objects.filter(is_active=True, is_main=True)
    #Вывод всех статей и пагинация (2 статьи на страницу)"""
    # краткое о нас
    abouts = ShortAbout.objects.all()
    # all_Articles = Article.objects.all()
    # paginator = Paginator(all_Articles, 4)
    # page = request.GET.get('page')
    #
    # try:
    #     articles = paginator.page(page)
    # except PageNotAnInteger:
    #     articles = paginator.page(1)
    # except EmptyPage:
    #     articles = paginator.page(paginator.num_pages)
    # context = {'articles': articles}
    # image_main = {'images_main': images_main}
    return render(request, 'content.html', locals())

def article(request,article_id=1):
    """Вывод одной конкретной статьи """
    # краткое о нас
    abouts = ShortAbout.objects.all()
    # articles = Article.objects.get(id=article_id)
    # features = Features.objects.filter(features_article_id=article_id)
    # return render(request, 'home/article.html', locals())
    return render_to_response('home/articles.html', {'article': Article.objects.get(id=article_id),
                                               'features': Features.objects.filter(features_article_id=article_id),
                                               'abouts': abouts})

    # new imports that go at the top of the file
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template

    # our view
def contact(request):
    abouts = ShortAbout.objects.all()
    form_class = ContactForm
         # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_email = request.POST.get('contact_email', '')
            form_content = request.POST.get('content', '')
                # Email the profile with the
                # contact information
            template = get_template('contact_template.txt')
            context = {'contact_name': contact_name, 'contact_email': contact_email, 'form_content': form_content}
            content = template.render(context)
            email = EmailMessage("New contact form submission", content, "Your website" + '', ['gidrosave@gmail.com'], headers={'Reply-To': contact_email})
            email.send()
        # return render('contact')
        # Переходим на другую страницу, если сообщение отправлено
#         return HttpResponseRedirect('/contacts/thanks/')
    return render(request, 'contacts/contacts.html', {
        'form': form_class,'abouts': abouts,})
#
# def thanks(reguest):
#     thanks = 'thanks'
#     return render(reguest, 'thanks.html', {'thanks': thanks})

def blog(request):
    # article = {'article': Article.objects.get(id=article_id)}
    #Вывод всех статей и пагинация (2 статьи на страницу)"""
    # краткое о нас
    # images_main = ContentImages.objects.filter(is_active=True, is_main=True)
    abouts = ShortAbout.objects.all()
    blogs_main = BlogImages.objects.filter(is_active=True, is_main=True)
    # paginator = Paginator(all_Articles, 1)
    # page = request.GET.get('page')
    #
    # try:
    #     articles = paginator.page(page)
    # except PageNotAnInteger:
    #     articles = paginator.page(1)
    # except EmptyPage:
    #     articles = paginator.page(paginator.num_pages)
    # context = {'articles': articles}
    return render(request, 'blog.html', locals())

def blogpost(request,article_id=1):
    """Вывод одной конкретной статьи """
    # краткое о нас
    abouts = ShortAbout.objects.all()
    # articles = Article.objects.get(id=article_id)
    # features = Features.objects.filter(features_article_id=article_id)
    # return render(request, 'home/article.html', locals())
    return render_to_response('article/blogpost.html', {'articles': Blog.objects.get(id=article_id),'abouts': abouts, 'article': Blog.objects.all()})

home/templates/about.html
<!DOCTYPE html>
{% load embed_video_tags %}
{% load staticfiles %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<title>Gidroave</title>
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
		<!-- google fonts -->
		<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700%7COpen+Sans:400,800italic,800,700italic,700,600italic,600,400italic,300italic,300%7CLibre+Baskerville:400,400italic,700%7CLato:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
		<!-- Bootstrap -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/skin.less' %}">
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){

			$(window).scroll(function(){
			    if ($(this).scrollTop() > 100) {
			$('.scrollup').fadeIn();
				} else {
			$('.scrollup').fadeOut();
				}
			});

			$('.scrollup').click(function(){
			$("html, body").animate({ scrollTop: 0 }, 600);
			return false;
				});

			});
		</script>
		 <style>
   				.leftimg {
    				float:left; /* Выравнивание по левому краю */
    				margin: 7px 7px 7px 0; /* Отступы вокруг картинки */
   					}
   				.rightimg  {
    				float: right; /* Выравнивание по правому краю  */
    				margin: 7px 0 7px 7px; /* Отступы вокруг картинки */
   					}
		 </style>
	</head>
	<body>
		<!--Wrapper Section Start Here -->
		<div id="wrapper">

 <div id="pageloader" class="row m0">
        <div class="loader-item"><img src="{% static 'svg/grid.svg' %}" alt="loading"></div>
    </div> 
			<!--header Section Start Here -->
		<header id="header">
				<div class="primary-header">
					<div class="container">
						<div class="row">
							<div class="col-sm-5 left-header">
							<span>Добро пожаловать на сайт компании GidroSave</span>
							</div>
							<div class="col-sm-7 right-header">
								<ul>
									<li>
										<span class="num">Вызов специалиста: 8-915-346-11-32</span>
									</li>
									<li>
										<a href="mailto:gidrosave@gmail.com"><i class="fa fa-envelope-o"></i> gidrosave@gmail.com</a>
									</li>
									<li>
										<a href="#"><i class="fa fa-vk"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-instagram"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-facebook"></i></a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="secondry-header">
					<div class="container">
						<div class="row">
							<div class="col-xs-12 col-sm-4">
								<a href="{% url 'home:home' %}" class="logo"><img src="{% static 'img/logo2.png' %}" alt="logo" /></a>
							</div>
							<div class="col-xs-12 col-sm-8 menu-wrapper">
								<div class="button-wrapper">
									<button class="nav-button"></button>
								</div>
								<nav class="navigation">

									<ul class="menu">
										<li>
											<a href="{% url 'home:home' %}">Главная</a>

										</li>
										<li class="active">
											<a href="{% url 'home:about' %}">О Нас</a>
											<!--Возможное подменю-->
											<!--<ul class="submenu">-->
												<!--<li>-->
													<!--<a href="projects.html">projects</a>-->
												<!--</li>-->
												<!--<li>-->
													<!--<a href="projects-1.html">projects-1</a>-->
												<!--</li>-->
												<!--<li>-->
													<!--<a href="projects-2.html">projects-2</a>-->
												<!--</li>-->
												<!--<li>-->
													<!--<a href="projects-details.html">projects-details</a>-->
												<!--</li>-->
											<!--</ul>-->
										</li>
										<li>
											<a href="{% url 'home:articles' %}">Наши работы</a>
										</li>
										<!--<li>-->
											<!--<a href="#">Контакты</a>-->
											<!--Возможное подменю-->
											<!--<ul class="submenu">-->
												<!--<li>-->
													<!--<a href="about-us.html">about-us</a>-->
												<!--</li>-->
												<!--<li>-->
													<!--<a href="about-us-1.html">about-us-1</a>-->
												<!--</li>-->
												<!--<li>-->
													<!--<a href="faq.html">faq</a>-->
												<!--</li>-->
											<!--</ul>-->
										<!--</li>-->
										<li>
											<a href="{% url 'home:blog' %}">Статьи</a>
										</li>
										<li>
											<a href="{% url 'home:contact' %}">Контакты</a>
										</li>
									</ul>
								</nav>
								<a href="{% url 'home:contact' %}" class="quote">Задать вопрос</a>
							</div>

						</div>
					</div>
				</div>

			</header>
			<!--header Section End Here -->


			<!--content Section Start Here -->
			<div id="content">

				<div id="slider" class="banner-container parallax">
					<div class="container">
						<div class="row">
							<div class="col-xs-12">
								<h3>О Компании</h3>
							</div>
						</div>
					</div>
				</div>

				<div class="clearfix">
					<div class="container">
						<div class="row">
							<div class="col-xs-12">
								<div class="breadcrumbs-box">
									<ul class="clearfix">
										<li>
											<a href="#">home</a>
										</li>
										<li>
											about us
										</li>
									</ul>
								</div>
							</div>
							{% for about in context %}
							<div class="row" style="margin-left: 0px; margin-right: 0px;">
								<!--<div class="col-xs-12 col-sm-6 ">-->
								<div class="about-detail">
									<h3> {{ about.about_title }}<i></i></h3>
									<!--<div class="col-xs-12 col-sm-6 ">-->
										{% if about.about_image %}
										<div class="about-img" style="width: 366px; height: 320px;">
											<img src="{{ MEDIA_URL }}{{ about.about_image.url }}" alt="" class="rightimg" />
										{% endif %}
									<!--<img src="assets/img/image-17.jpg" alt="" />-->
									<!--<img src="assets/img/image-18.jpg" alt="" />-->
										</div>
									<!--</div>-->
									<p>
										{% autoescape off %}{{ about.about_text }}{% endautoescape %}
									</p>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
			<!--content Section End Here -->

			<!--footer Section Start Here -->
			<footer id="footer">


				<div class="contact-us-container">
					<div class="container">
						<div class="row">
							<div class="col-xs-12 animate-effect">
								<div class="box">
								</div>

								<div class="box call">
								</div>

								<div class="box" style="height: 128px">
									<ul class="clearfix">
									</ul>
								</div>

								<div class="box call">
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--contact-us container End Here -->

				<div class="primary-footer">
					<div class="container">
						<div class="row animate-effect">
							{% for about in abouts %}
							<div class="col-xs-12 col-sm-4">
								<h3>О Компании <i></i></h3>
								<p>
									{{ about.short_text }}
								</p>
							</div>
							{% endfor %}

							<div class="col-xs-12 col-sm-4">
								<h3>Навигация по сайту <i></i></h3>
								<ul class="list clearfix">
									<li>
										<a href="{% url 'home:home' %}">Главная</a>
									</li>
									<li>
										<a href="{% url 'home:about' %}">О нас</a>
									</li>
									<li>
										<a href="{% url 'home:articles' %}">Наши работы</a>
									</li>
									<li>
										<a href="{% url 'home:blog' %}">Статьи</a>
									</li>
									<li>
										<a href="{% url 'home:contact' %}">Контакты</a>
									</li>
									<!--Возможная ссылка-->
									<!--<li>-->
										<!--<a href="#">Contact us</a>-->
									<!--</li>-->
								</ul>
							</div>

							<div class="col-xs-12 col-sm-4">
								<h3>Наши контакты: <i></i></h3>
										<a href="#"><i class="fa fa-vk"></i></a>
										<a href="#"><i class="fa fa-instagram" style="padding-right: 20px; padding-left: 20px; padding-bottom: 10px;"></i></a>
										<a href="#"><i class="fa fa-facebook"></i></a>
								<address>
								<!--Адресс в Москве:<br>-->
								<!--ул.Мусы Джалиля,<br>-->
								<!--д.4, к.4,<br>-->
									<!--оффис №349<br>-->
								<i class="fa fa-phone"></i>
									8-915-346-11-32<br>
									<i class="fa fa-phone"></i>
									8-499-725-32-93<br>
								<i class="fa fa-envelope-o"></i>
									<a href="mailto:gidrosave@gmail.com">gidrosave@gmail.com</a>

								</address>
							</div>

						</div>

						<div class="row animate-effect">
							<div class="col-xs-12 copyright">
								<div class="col-sm-5 left-header">
									<span>Ly4ok666 | © 2017 Ly4ok_Industrial, All rights reserved</span>
								</div>
								<div class="col-sm-7 right-header">
								<ul>
									<li>
										<a href="mailto:ly4ok666@gmail.com"><i class="fa fa-envelope-o"></i>ly4ok666@gmail.com</a>
									</li>
									<li>
										<a href="#"><i class="fa fa-vk"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-instagram"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-facebook"></i></a>
									</li>
								</ul>
							<!--</div>-->
								<!--<span>Ly4ok666 | © 2017 Ly4ok_Industrial, All rights reserved</span>-->
							<!--</div>-->
							</div>
						</div>
					</div>
					</div>
				</div>
			</footer>
			<!--footer Section End Here -->
		</div>
		<!--Wrapper Section End Here -->

		<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/less.js' %}"></script>
		<script src="{% static 'js/jquery.bxslider.js' %}"></script>
		<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
		<script src="{% static 'js/site.js' %}"></script>
		<a href="#" class="scrollup">Наверх</a>
	</body>
</html>